### ISSUE TITLE
Arrays that are circular in certain dimensions

### ISSUE THREAD

**Issue by putianyi889** [Vexatos/CircularArrays.jl#26]
What I would appreciate is a way to construct a matrix that is circular in the first dimension while restricted in the other dimension (i.e. should be able to throw `BoundsError`)

There are two ways to achieve this:
- To add a size property that hard caps the bounds. This would introduce a dependency related to infinite indexing (e.g. `InfiniteArrays`). This is more straightforward on the surface but are prone to infinite loops at broadcast-like operations.
- To add a dim property that specifies the circular dimensions. `checkbounds` needs to be overloaded.

**Comment by juliohm** [comment]
Perhaps this a feature for a higher level package. We have that in our Grid
types in Meshes.jl for example.

Em qui., 18 de jan. de 2024 09:11, Tianyi Pu ***@***.***>
escreveu:

**Comment by Vexatos** [comment]
I agree that this should go in a different package that adds bound checks fitting your particular needs.
